development:
  host: localhost
  folder: /usr/local/WowzaMediaServer/content
  protocol: rtmp
  application: vod
  port: 1935

test:
  host: localhost
  folder: /usr/local/WowzaMediaServer/content
  protocol: rtmp
  application: rvidi
  port: 1935

staging:

demo:

production:
  host: server???
  folder: folder????

