development:
  host: localhost
  folder: /usr/local/WowzaMediaServer-3.6.3/content/rvidi
  protocol: rtmp
  application: rvidi
  port: 1935
  ssh_keys: [config/ssh/id_rsa.pub]
  username: root


test:
  host: latizana.com
  folder: /usr/local/WowzaMediaServer-3.6.3/content/rvidi
  protocol: rtmp
  application: rvidi
  port: 1935
  ssh_key: [config/ssh/id_rsa.pub]
  username: root


staging:

demo:

production:
  host: server???
  folder: folder????

